apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-kon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-kon
  template:
    metadata:
      labels:
        app: devops-kon
    spec:
      containers:
        - name: devops-kon
          image: khalilarfaoui/devops-kon  # Update to the correct image name
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"   # Adjust memory if needed
              cpu: "500m"
            limits:
              memory: "2Gi"   # Adjust memory if needed
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-kon-service  # Update to match the new app name
spec:
  selector:
    app: devops-kon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
