name: Build and Test Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérification du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuration de Java (utilisation de Temurin pour JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Remplacez 'adoptopenjdk' par 'temurin'

      # Caching des dépendances Maven pour accélérer les builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Installation de Maven et exécution du build
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Exécution des tests
      - name: Run tests with Maven
        run: mvn test
