name: Deploy to Nexus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure .m2 directory exists
        run: mkdir -p ~/.m2

      - name: Write Maven settings from secret
        run: echo "${{ secrets.MAVEN_SETTINGS }}" > ~/.m2/settings.xml

      - name: Verify settings.xml content
        run: cat ~/.m2/settings.xml

      - name: Deploy to Nexus
        run: mvn clean deploy
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
