name: Build and Deploy to Nexus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker --version
