name: Deploy to Nexus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Deploy to Nexus
        run: mvn clean deploy
