name: Build and Deploy to Nexus

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: sudo apt-get install maven

      - name: Nexus Deploy
        run: |
          cd C:/Users/MSI/Desktop/devops/jenkins
          mvn clean deploy